apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-injection-go-app
  labels:
    app: shell-injection-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-injection-go-app
  template:
    metadata:
      labels:
        app: shell-injection-go-app
    spec:
      containers:
      - name: shell-injection-go-app
        image: igoritosousa22/shell-injection-go:v1
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: shell-injection-go-app-service
spec:
  selector:
    app: shell-injection-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      name: svc-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: s.example.com
      http:
        paths:
          - path: /inject
            pathType: Prefix
            backend:
              service:
                name: shell-injection-go-app-service
                port:
                  name: svc-port
